### ISSUE TITLE
Global functions and variables across files

### ISSUE THREAD

**Issue by towerofnix** [commandstudio/commandstudio#2]
For example I might write a small library for using `tellraw`. It would be much easier to load it as a separate file in the project rather than import it at the top of every file.

Another thing - if I have to import it into every file, and then end up editing the function in one file, it won't get updated in all the other files! I'd have to copy and paste the new, updated function _everywhere, again!_

**Comment by lemarcantoine** [comment]
The fact that you have to include a file to share functions will not change because writing a single line at the top of your files is not very constraining. Plus CommandStudio is inspired by other "regular" programming languages.

The second point is an other thing. Maybe adding a "Compile whole project" could resolve this issue? An other solution would be to track in each file when your function is used but it would be really heavy.

**Comment by towerofnix** [comment]
> The fact that you have to include a file to share functions will not change because writing a single line at the top of your files is not very constraining.

Hmm, that's not at all difficult to do - but I didn't see anything in the manual about includes..

**Comment by lemarcantoine** [comment]
Oh right I forgot about them. ^^'

It works like that:
`include file_name`

**Comment by towerofnix** [comment]
That's great, thanks!
